FROM ubuntu:16.04

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash
RUN apt install -y nodejs
COPY . .
ENV FRONT_URL=http://localhost:3000
RUN npm install
CMD npm start